
### model
model_name_or_path: /back-up/gzy/meta-comphrehensive-rag-benchmark-starter-kit/models/LLM/Meta-Llama-3-8B-Instruct

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all

### dataset
dataset: WebQuestion_post
template: llama3
cutoff_len: 4096
max_samples: 999999999
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: /back-up/gzy/ft/llama3-8b/post/WebQuestion/v2
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 2.0e-4
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 500
